# Generated by Django 3.1.3 on 2021-02-02 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210201_1633'),
        ('reservations', '0002_auto_20210201_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='customerReserving',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.customer'),
        ),
    ]
