# Generated by Django 3.1.3 on 2021-01-30 22:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default=None, max_length=50)),
                ('firstName', models.CharField(default=None, max_length=20)),
                ('lastName', models.CharField(default=None, max_length=20)),
                ('street', models.CharField(default=None, max_length=20)),
                ('city', models.CharField(default=None, max_length=100)),
                ('state', models.CharField(default=None, max_length=20)),
                ('zipcode', models.CharField(default=None, max_length=20)),
                ('phoneNumber', models.CharField(default=None, max_length=20)),
                ('verified', models.CharField(choices=[('Annual', 'Annual Pass Holder'), ('Resident', 'Town of Leesburg Resident'), ('Neither', 'Neither'), ('UnVerified', 'UnVerified')], max_length=20)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
